# Generated by Django 5.2.7 on 2026-04-05 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_creditrecord_business_customer_business'),
        ('inventory', '0002_product_business_supplier_business'),
        ('sales', '0003_alter_invoice_total_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('customer', 'Customer Order'), ('supplier', 'Supplier Order')], default='customer', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.supplier'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
    ]
