# Generated by Django 6.0.3 on 2026-08-16 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_business_tenant'),
        ('tenants', '0006_subscriptionplan_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
    ]
