# Generated by Django 6.0.3 on 2026-08-06 21:16

from django.db import migrations, models


def blank_to_null(apps, schema_editor):
    Employee = apps.get_model('hr', 'Employee')
    Employee.objects.filter(national_id='').update(national_id=None)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='national_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(blank_to_null, noop_reverse),
    ]
