# Generated by Django 6.0.3 on 2026-04-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='business',
        ),
    ]
