# Generated by Django 6.0.3 on 2026-08-19 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('salaries', 'Salaries & Wages'), ('transport', 'Transport'), ('utilities', 'Utilities'), ('electricity', 'Electricity'), ('water', 'Water'), ('marketing', 'Marketing'), ('gas_fuel', 'Gas/Fuel'), ('maintenance', 'Maintenance'), ('food_production', 'Food/Production'), ('other', 'Other')], max_length=20),
        ),
    ]
