# Generated by Django 6.0.3 on 2026-08-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_backfill_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='receipt_footer',
            field=models.CharField(blank=True, default='Thank you for your business!', help_text='Message shown at the bottom of printed receipts.', max_length=200),
        ),
    ]
