# Generated by Django 6.0.3 on 2026-08-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0006_subscriptionplan_subscriptionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('OWNER', 'CEO'), ('MANAGER', 'Manager'), ('ACCOUNTANT', 'Accountant'), ('SALES_STAFF', 'Sales Staff'), ('INVENTORY_MANAGER', 'Inventory Manager'), ('STAFF', 'Employee')], default='STAFF', max_length=20),
        ),
    ]
