# Generated by Django 6.0.3 on 2026-08-19 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0007_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
