# Generated by Django 6.0.3 on 2026-04-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_product_business_supplier_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='business',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='business',
        ),
    ]
