# Generated by Django 6.0.3 on 2026-08-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_alter_product_minimum_stock_alter_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(blank=True, help_text='WhatsApp number in international format, e.g. 254712345678', max_length=20),
        ),
    ]
