# Generated by Django 5.2.17 on 2026-10-01 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_goodsreceipt_goodsreceiptline_stockcount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost_price',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Positive purchase cost per unit is required for inventory valuation.',
                max_digits=10,
            ),
        ),
    ]