# Generated by Django 6.0.3 on 2026-04-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_creditrecord_business_customer_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditrecord',
            name='business',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='business',
        ),
    ]
