# Generated by Django 6.0.3 on 2026-08-15 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_alter_creditrecord_tenant_alter_customer_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Free-form relationship notes -- preferences, history, anything worth remembering.'),
        ),
    ]
