"""
Django settings for 14xlevel ERP project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    return os.environ.get(name, str(default)).strip().lower() in ('1', 'true', 'yes', 'on')


def env_list(name):
    return [item.strip() for item in os.environ.get(name, '').split(',') if item.strip()]


# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# Each hosting platform injects the app's own public hostname. Their presence is
# also how we know we are not on a laptop: DEBUG then defaults to off, so
# forgetting to set it cannot expose tracebacks and settings to the internet.
PLATFORM_HOST_VARS = (
    'VERCEL_PROJECT_PRODUCTION_URL',  # stable production domain
    'VERCEL_URL',                     # per-deployment preview domain
    'RENDER_EXTERNAL_HOSTNAME',
    'RAILWAY_PUBLIC_DOMAIN',
)
ON_PLATFORM = any(os.environ.get(name) for name in PLATFORM_HOST_VARS)

DEBUG = env_bool('DEBUG', not ON_PLATFORM)

# In production SECRET_KEY must come from the environment. The insecure literal
# is only a convenience for local development, where DEBUG is on.
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        # Report which of the other expected variables arrived. If some did,
        # this key alone is missing or misspelled; if none did, the deployment
        # is not receiving its environment at all and the fix is in the host's
        # settings rather than here. Names only — never log the values.
        _expected = (
            'DATABASE_URL', 'SUPABASE_S3_ENDPOINT', 'SUPABASE_S3_REGION',
            'SUPABASE_S3_BUCKET', 'SUPABASE_S3_ACCESS_KEY', 'SUPABASE_S3_SECRET_KEY',
        )
        _present = [name for name in _expected if os.environ.get(name)]
        # When none arrive, the useful question is what the host *did* inject,
        # so list every name. Platform variables showing up while ours do not
        # narrows it to how they are configured, not whether they exist.
        _all = sorted(os.environ)
        raise RuntimeError(
            'SECRET_KEY environment variable must be set when DEBUG is off. '
            f'Other expected variables present: {_present or "NONE"}. '
            + (
                'None of them arrived, so this deployment is not receiving its '
                'environment variables.'
                if not _present else
                'Others did arrive, so SECRET_KEY specifically is missing or misspelled.'
            )
            + f' Environment holds {len(_all)} names: {_all}'
        )
    SECRET_KEY = 'django-insecure-ve8ddzzo7r=kb45my%ivno5n9n@cy-iv8@nmhe(%f+tf_3%w6u'

ALLOWED_HOSTS = env_list('ALLOWED_HOSTS') or ['127.0.0.1', 'localhost', 'testserver']

# Trust the platform's own hostname automatically so a fresh deploy answers
# before any custom domain is attached. Vercel gives every preview deployment a
# different hostname, so this cannot be hardcoded.
for _host_var in PLATFORM_HOST_VARS:
    _host = os.environ.get(_host_var)
    if _host and _host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_host)

# Django 4+ requires the scheme here, and form POSTs 403 without it behind HTTPS.
CSRF_TRUSTED_ORIGINS = env_list('CSRF_TRUSTED_ORIGINS') or [
    f'https://{host}' for host in ALLOWED_HOSTS if host not in ('127.0.0.1', 'localhost', 'testserver')
]

if not DEBUG:
    # The platform terminates TLS and forwards the original scheme in this header.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = env_bool('SECURE_SSL_REDIRECT', True)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    'tenants',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'inventory',
    'sales',
    'customers',
    'expenses',
    'dashboard',
    'core',
    'payroll',
    'hr',
    'accounting',
    'guardian',  # For object-level permissions
    'rest_framework',  # For API
    'rest_framework_simplejwt',  # For JWT
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'guardian.backends.ObjectPermissionBackend',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Must sit directly below SecurityMiddleware so it can serve static files
    # without a separate web server in front.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'tenants.middleware.TenantMiddleware',  # Custom tenant middleware
    'tenants.middleware.SubscriptionGateMiddleware',
]

ROOT_URLCONF = 'realkukuERP_System.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'realkukuERP_System.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Production supplies DATABASE_URL (Postgres). Without it we fall back to the
# local SQLite file so development keeps working with no extra setup.
DATABASE_URL = os.environ.get('DATABASE_URL')

# Supabase's Supavisor pooler in transaction mode (port 6543) hands each request
# a different backend connection, so nothing may be held open across requests:
# persistent connections would pin a pooled slot, and server-side cursors would
# be opened on one backend and read from another, failing intermittently under
# load. Session mode (5432) has neither restriction.
PGBOUNCER_MODE = env_bool('PGBOUNCER_MODE', False) or ':6543' in (DATABASE_URL or '')

if DATABASE_URL:
    import dj_database_url

    DATABASES = {
        'default': dj_database_url.parse(
            DATABASE_URL,
            conn_max_age=0 if PGBOUNCER_MODE else 600,
            conn_health_checks=not PGBOUNCER_MODE,
            ssl_require=not DEBUG,
        )
    }
    if PGBOUNCER_MODE:
        DATABASES['default']['DISABLE_SERVER_SIDE_CURSORS'] = True
else:
    DB_PATH = BASE_DIR / '14xlERP' / 'db.sqlite3'
    DB_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Use a user-writable SQLite path so local admin and data writes work reliably.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': str(DB_PATH),
        }
    }

AUTH_USER_MODEL = 'tenants.User'
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/login/'

# Password reset emails print to the terminal unless SMTP credentials are set.
# Set EMAIL_HOST (plus user/password) in the environment to send real mail —
# without it, password reset silently does nothing in production.
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')

if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
    EMAIL_USE_TLS = env_bool('EMAIL_USE_TLS', True)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'no-reply@14xlevel-erp.local')

# WhatsApp Business Cloud API (Meta), used to alert suppliers when a
# purchase order is sent to them. Needs real setup only the business
# owner can do: a Meta Business Account, a verified WhatsApp Business
# phone number, and an approved message template (business-initiated
# WhatsApp messages must use a pre-approved template -- free-form text
# only works within 24 hours of the recipient messaging first). Without
# these three values, sales.whatsapp.send_supplier_order_alert() no-ops
# with a clear 'not_configured' status rather than pretending to send.
WHATSAPP_API_TOKEN = os.environ.get('WHATSAPP_API_TOKEN', '')
WHATSAPP_PHONE_NUMBER_ID = os.environ.get('WHATSAPP_PHONE_NUMBER_ID', '')
WHATSAPP_TEMPLATE_NAME = os.environ.get('WHATSAPP_TEMPLATE_NAME', 'purchase_order_alert')

# M-Pesa Daraja API (Safaricom), for STK Push ("Lipa Na M-Pesa Online")
# customer payments on invoices. Needs a Safaricom Daraja developer
# account, a paybill/till shortcode, and (for production) a signed
# contract with Safaricom -- see MPESA_SETUP.md. Without these,
# sales.mpesa.initiate_stk_push() reports 'not_configured' instead of
# pretending to send a payment prompt.
MPESA_CONSUMER_KEY = os.environ.get('MPESA_CONSUMER_KEY', '')
MPESA_CONSUMER_SECRET = os.environ.get('MPESA_CONSUMER_SECRET', '')
MPESA_SHORTCODE = os.environ.get('MPESA_SHORTCODE', '')
MPESA_PASSKEY = os.environ.get('MPESA_PASSKEY', '')
# 'sandbox' while testing against Safaricom's test environment,
# 'production' only once the paybill/till is live.
MPESA_ENVIRONMENT = os.environ.get('MPESA_ENVIRONMENT', 'sandbox')
# Must be a real, publicly reachable HTTPS URL -- Safaricom's servers
# POST the payment result here. localhost cannot receive this without a
# tunnel (ngrok etc.); it only really works once deployed.
MPESA_CALLBACK_URL = os.environ.get('MPESA_CALLBACK_URL', '')


# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

# Uploaded files (HR resumes, payroll receipts). On Railway/Render this path
# must live on an attached persistent disk, otherwise uploads are lost on
# every redeploy — set MEDIA_ROOT to the mounted volume path.
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

# Vercel runs no build step, so collectstatic never happens there. A manifest
# storage would then raise at runtime on the first {% static %} tag and take
# /admin/ down with it. Letting WhiteNoise resolve through the staticfiles
# finders means the admin CSS works with nothing collected and nothing
# committed, trading away hashed filenames — acceptable here, since no project
# template uses {% static %} and only Django's own admin depends on it.
WHITENOISE_USE_FINDERS = env_bool('WHITENOISE_USE_FINDERS', True)

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': (
            'django.contrib.staticfiles.storage.StaticFilesStorage'
            if WHITENOISE_USE_FINDERS
            # Hashes filenames and gzips them so assets can be cached forever.
            # Requires collectstatic to have run at build time.
            else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
        ),
    },
}

# Supabase Storage speaks S3, so uploads can go to object storage instead of the
# container filesystem. Set all four variables to switch it on; leaving any unset
# keeps the local filesystem, which is what development wants.
SUPABASE_S3_ENDPOINT = os.environ.get('SUPABASE_S3_ENDPOINT', '')
SUPABASE_S3_ACCESS_KEY = os.environ.get('SUPABASE_S3_ACCESS_KEY', '')
SUPABASE_S3_SECRET_KEY = os.environ.get('SUPABASE_S3_SECRET_KEY', '')
SUPABASE_S3_BUCKET = os.environ.get('SUPABASE_S3_BUCKET', '')

if all((SUPABASE_S3_ENDPOINT, SUPABASE_S3_ACCESS_KEY, SUPABASE_S3_SECRET_KEY, SUPABASE_S3_BUCKET)):
    STORAGES['default'] = {
        'BACKEND': 'storages.backends.s3.S3Storage',
        'OPTIONS': {
            'endpoint_url': SUPABASE_S3_ENDPOINT,
            'access_key': SUPABASE_S3_ACCESS_KEY,
            'secret_key': SUPABASE_S3_SECRET_KEY,
            'bucket_name': SUPABASE_S3_BUCKET,
            'region_name': os.environ.get('SUPABASE_S3_REGION', 'us-east-1'),
            # Supabase only serves path-style URLs; the default virtual-host
            # style resolves to a hostname that does not exist.
            'addressing_style': 'path',
            # Supabase rejects SigV2. Uploads negotiate v4 on their own, but
            # presigned download URLs fall back to v2 and 403 without this.
            'signature_version': 's3v4',
            # The bucket is private, so links are time-limited signed URLs.
            # Payroll receipts and resumes should not be world-readable.
            'querystring_auth': True,
            'querystring_expire': 3600,
            'file_overwrite': False,
            'default_acl': None,
        },
    }
