# Generated by Django 6.0.3 on 2026-08-22 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('chat', 'Message'), ('report', 'Report')], default='chat', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
