# Generated by Django 6.0.3 on 2026-04-18 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_order_order_type_order_supplier_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='business',
        ),
        migrations.RemoveField(
            model_name='order',
            name='business',
        ),
    ]
