# Generated by Django 6.0.3 on 2026-08-15 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_dailysalesentry_created_by_invoice_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='sale_channel',
            field=models.CharField(choices=[('retail', 'Retail'), ('wholesale', 'Wholesale'), ('online', 'Online')], default='retail', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
