# Generated by Django 6.0.3 on 2026-08-15 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_invoiceitem_sale_channel_alter_invoiceitem_qty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier_notification_status',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
