# Generated by Django 6.0.3 on 2026-08-22 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_goodsreceipt_goodsreceiptline_stockcount_and_more'),
        ('sales', '0014_invoice_due_date_payment_notes_payment_recorded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='inventory.location'),
        ),
    ]
